# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubehcl" do
  name "kubehcl"
  desc ""
  homepage ""
  version "0.2.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubehcl"

  on_macos do
    on_intel do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_darwin_amd64.tar.gz"
      sha256 "3c0da8485a62c74f7f0e6f985ecf7fdb7834c4ea3e4b9798d65c0953506a20d8"
    end
    on_arm do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_darwin_arm64.tar.gz"
      sha256 "74559fe89705e57c8eb5a1fae766c52e5b0ba6930d60fdcce718683cce7cc103"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_linux_amd64.tar.gz"
      sha256 "257167e2b6a1a6e1bbf19a720f77424e90bee0e5cd73a086f7b8961563a20b7a"
    end
    on_arm do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_linux_arm64.tar.gz"
      sha256 "711cd4a25b0e7c7a084d9266bde33306c2e913e50e7cea270bb81a897fe89d33"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubehcl"]
    end
  end

  # No zap stanza required
end
