# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubehcl" do
  name "kubehcl"
  desc ""
  homepage ""
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubehcl"

  on_macos do
    on_intel do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_darwin_amd64.tar.gz"
      sha256 "d38ea247da2d41bab7c80c656328aca100aaa265fd75eddd66e53230e54a2563"
    end
    on_arm do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_darwin_arm64.tar.gz"
      sha256 "42c55b83fe1f3a2b1f4ccb3f022c9c288953463d0acb9edeea29c374e32e1821"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_linux_amd64.tar.gz"
      sha256 "37c2852075768fa5dafe95c710951508c57faaf2c9c11033631a0027a9063b89"
    end
    on_arm do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_linux_arm64.tar.gz"
      sha256 "66217543d5d9a97e08bfb0ae08a969f5b8ce893f8e091e778da9b9ca2f78f025"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubehcl"]
    end
  end

  # No zap stanza required
end
