# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubehcl" do
  name "kubehcl"
  desc ""
  homepage ""
  version "0.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubehcl"

  on_macos do
    on_intel do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_darwin_amd64.tar.gz"
      sha256 "c080b2321266b933aabd3145eb1a7ee6ce7a378970357173b248c8c56dc196e6"
    end
    on_arm do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_darwin_arm64.tar.gz"
      sha256 "8c1f67c0e4779f3469d714929d9c80907c410ae27fbb84bd751258f757bfd1ff"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_linux_amd64.tar.gz"
      sha256 "ac0e74484134e8d1e694159dcca13ac09da77b7e87276c7373c6207622a33bb7"
    end
    on_arm do
      url "https://github.com/yanir75/kubehcl/releases/download/v#{version}/kubehcl_#{version}_linux_arm64.tar.gz"
      sha256 "007344f9325242d4b8ba6c28a145725fd61b41832a9385bd7816b1c15460a724"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubehcl"]
    end
  end

  # No zap stanza required
end
